development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url:  redis://redistogo:58f441960100a584812f07e9b9f8e0a8@hammerjaw.redistogo.com:11629/
  channel_prefix: message_me_production
